version: '3.0'

services: 
  web: 
    build: 
      context: ./docker/web
    volumes:
      - .:/app
      - ./docker/web/sites-enabled:/etc/apache2/sites-enabled
    ports:
      - 8080:80
      - 8443:443
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
