version: '3.0'

services: 
  dusk:
    build: 
      context: ./docker/web
    volumes:
      - .:/app
    working_dir: /app
    command: php artisan dusk
    environment:
      - DUSK_DRIVER_URL=http://selenium:4444/
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:JdOrYkK358m+ir9/8MQezti4yTUuvs35IWmU+SgjCZk=
      - APP_DEBUG=false
      - APP_URL=http://web:8000
 
      - LOG_CHANNEL=stack
 
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
 
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
 
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
 
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=admin@example.com
      - MAIL_FROM_NAME="${APP_NAME}"

      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=

      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_APP_CLUSTER=mt1

      - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
  web:
    working_dir: /app
    command: php artisan serve --host 0.0.0.0
    ports:
      - 8000:8000
    environment:
      - APP_DEBUG=true
      - APP_URL=http://web:8000
  db:
    restart: always
    volumes:
      - ./docker/mysql/data_test:/var/lib/mysql
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
